version: '3.8'
services:
  airflow:
    build: 
      context: ./dockerfiles
      dockerfile: 'Dockerfile.airflow'
    volumes:
      - ./dags:/opt/airflow/dags
      - logs:/opt/airflow/logs
      # - ./entrypoint.sh:/entrypoint.sh  # Copy entrypoint.sh script
      - jars:/opt/jars
    ports:
      - 8080:8080
    environment:
      - AIRFLOW_HOME=/opt/airflow
  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  spark-master:
    image: airflow-spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8090:8080'
    volumes:
      - ./dags:/opt/bitnami/spark/dags
      - jars:/opt/jars
  spark-worker:
    image: airflow-spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./dags:/opt/bitnami/spark/dags
      - jars:/opt/jars
    depends_on:
      - spark-master
    
volumes:
  logs:
  data:
  jars:
